#!/bin/bash
# Script para limpeza do cache do Squid
# Por Marcelo Leães - marcelo@eth1.com.br

echo -e "--------------------------------------------------------------" >> /var/log/squid/cleaner.log
echo -e "Parando Squid - `date "+%d-%m-%Y"`" >> /var/log/squid/cleaner.log
/etc/init.d/squid stop
cd /var/spool/squid/
echo -e "Limpando Squid - `date "+%d-%m-%Y"`" >> /var/log/squid/cleaner.log
rm -rf *
echo -e "Reconstruindo Squid - `date "+%d-%m-%Y"`" >> /var/log/squid/cleaner.log
squid -z
echo -e "Iniciando Squid - `date "+%d-%m-%Y"`" >> /var/log/squid/cleaner.log
/etc/init.d/squid start
echo -e "--------------------------------------------------------------" >> /var/log/squid/cleaner.log
exit 0
