#!/bin/bash
echo -n "Parando squid."
/etc/init.d/squid stop
cd /var/spool/squid/
echo -n "Limpando squid."
rm -Rfv *
echo -n "Excluindo arquivos..."
echo -n "Reconstruindo estrutura do cache."
/usr/sbin/squid -z
echo -n "Ativando squid"
/etc/init.d/squid start
/usr/sbin/squid -k reconfigure
