#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mNome do novo usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mSenha para o usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mQuantos dias usuario $name deve durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mQual o limite de logins:\033[0;37m"; read -p " " limite
	echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name ja existe\033[0m"
	else
		echo -e ""$verde"           Conta Criada com Sucesso"
echo " "
echo -e ""$amarelo"IP:"$branco" $IP"
echo -e ""$amarelo"Portas SSH:"$branco" 443 e 22"
echo -e ""$amarelo"Login:"$branco" $nome"
echo -e ""$amarelo"Senha:"$branco" $senha"
echo -e ""$amarelo"Proxy:"$branco" $IP"
echo -e ""$amarelo"Portas:"$branco" 8080 80 8799 e 3128"
echo -e ""$amarelo"Validade:"$branco" $validadebr"
echo "          Conta Criada com Sucesso" >/root/$nome.txt
echo "
" >>/root/$nome.txt
echo "IP: $IP
Portas SSH: 443 e 22
Login: $nome
Senha: $senha
Proxy: $IP
Portas: 8080 80 8799 e 3128
Validade: $validadebr" >>/root/$nome.txt
