#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/VpsPack2dir ]
then
echo ""
else
mkdir /etc/VpsPack2dir
fi

if [ -d /etc/VpsPack2dir/senha ]
then
echo ""
else
mkdir /etc/VpsPack2dir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPack2dir/limite
fi

clear
echo -e " \033[1;37m  VpsPack2  1.1  [Para Remover o VpsPack2 use o comando(desistalar)]\033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] limit \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[2] criarusuario \033[1;30m(Criar usuarios)\033[1;33m
[3] redefinirusuario \033[1;30m(Opções para mudanças no usuario)\033[1;33m
[4] userback \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] bloquearfirewall \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[6] resertafirewall \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m
[7] instalar-addhost \033[1;30m(Faz a preparaçao para add-host)\033[1;33m
[8] addhost \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[9] sshmonitor \033[1;30m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;33m
[10] beckuperuser \033[1;30m(Backup dos usuarios para reinstalação futura)\033[1;33m
[11] Rest-Users \033[1;30m(Restaurar usuarios feito backup)\033[1;33m
[12] detalhesusuario \033[1;30m(Mostra informações sobre os usuarios !!)\033[1;33m
[13] banner \033[1;30m(Banner mensagem no ssh)\033[1;33m
[14] speedtest \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[15] systemdetalhes \033[1;30m(Detalhes sobre o Sistema)\033[1;33m
[16] detalhes \033[1;30m(Detalhes sobre o VpsPack2)\033[1;33m
[17] confvps \033[1;30m(Configurar Sua Vps)\033[0m"
read -p ": " opcao

case $opcao in
 1)
  read -p "Usuario: " user
  read -p "Limite de Conexoes: " limit
  limit $user $limit;;
 2)
  criarusuario;;
 3)
  redefinirusuario;;
 4)
  userback;;
 5)
  bloquearfirewall;;
 6)
  resertafirewall;;
 7)
  instalar-addhost;;
 8)
  addhost;;
 9)
  sshmonitor;;
 10)
  beckuperuser;;
 11)
  read -p "Em qual diretorio esta o arquivo de Backup: " arq 
  restaurar-usuarios $arq;;
 12)
  detalhesusuario;;
 13)
  banner;;
 14)
  speedtest;;
 15)
  systemdetalhes;;
 16)
  detalhes;;
 17)
  confvps;;
  18)
  desinstalar;;
  *)
  id > /dev/null 2> /dev/null
esac
